### PR TITLE
Fix `LifetimeFree` impl for `NonZeroUsize`

### PR DESCRIPTION
**Pull request by NobodyXu**
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by NobodyXu** [comment]
@sagebind I just realized that `LifeTimeFree` isn't implemented for `NonZeroUsize` when trying to use this in https://github.com/ParkMyCar/compact_str/pull/16.

**Review by sagebind — APPROVED** [review]
Good catch!

**Comment by NobodyXu** [comment]
@sagebind Can we merge this in and release a new minor version?

**Comment by sagebind** [comment]
Yep, that's my intention!

**Comment by sagebind** [comment]
Version 0.2.1 is now published with this addition!

**Pull request merged**
